version: "3.7"

services: 
  mongodb-app:
    image: mongo
    container_name: mongodb-app
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports: 
      - 27017:27017
    volumes: 
       - /data/db
  
  app:
    build: .
    container_name: hvex
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    # links: 
    #   - mongodb-app
    # depends_on: 
    #   - mongodb-app